### PR TITLE
Simplify boot partition fixup

### PR DESCRIPTION
**Pull request by koivunen**

### CODE REVIEW

**Comment by noahbliss** [comment]
Looks good but obligatory "ewww nano"

**Comment by noahbliss** [comment]
I'm still thinking about whether to merge this or not. I see it would be easier to copy-paste but I'd rather users know what they are doing as they do it. We already have a quick copy-paste in the speedread.md file. Might still merge it anyways, but will think about it some more. Thanks for the effort in either case!

**Comment by koivunen** [comment]
This should probably be eventually converted into a full shell script that tries to figure out how much damage would be caused and whether or not to proceed based on what is found.

In the meanwhile, a checklist-style listing of commands I am trying to PR (similar to speedread if not exactly the same) is IMO less error-prone than only telling a person abstractly what it is that you want done. 
I feel that at least my brain processes example commands with comments with better accuracy than abstract messages even if I know what command to run in the end but I do see the point that the brain wants to just execute the commands without forethought and then it might be too late to fix things when something goes wrong.

**Review by noahbliss — APPROVED** [review]

**Comment by noahbliss** [comment]
this sat for long enough, had to go one way or the other, haha sorry for the delay

**Pull request merged**
